apiVersion: v1
kind: Service
metadata:
  name: fyyc
spec:
  type: LoadBalancer
  selector:
    app: fyyc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer